class CountryCode {
  final String name;
  final String flag;
  final String dialCode;
  const CountryCode({required this.name, required this.flag, required this.dialCode});
  @override
  String toString() => '$flag $dialCode';
}

const kCountryCodes = [
  CountryCode(name: 'India', flag: '🇮🇳', dialCode: '+91'),
  CountryCode(name: 'United States', flag: '🇺🇸', dialCode: '+1'),
  CountryCode(name: 'United Kingdom', flag: '🇬🇧', dialCode: '+44'),
  CountryCode(name: 'Afghanistan', flag: '🇦🇫', dialCode: '+93'),
  CountryCode(name: 'Albania', flag: '🇦🇱', dialCode: '+355'),
  CountryCode(name: 'Algeria', flag: '🇩🇿', dialCode: '+213'),
  CountryCode(name: 'Andorra', flag: '🇦🇩', dialCode: '+376'),
  CountryCode(name: 'Angola', flag: '🇦🇴', dialCode: '+244'),
  CountryCode(name: 'Argentina', flag: '🇦🇷', dialCode: '+54'),
  CountryCode(name: 'Armenia', flag: '🇦🇲', dialCode: '+374'),
  CountryCode(name: 'Australia', flag: '🇦🇺', dialCode: '+61'),
  CountryCode(name: 'Austria', flag: '🇦🇹', dialCode: '+43'),
  CountryCode(name: 'Azerbaijan', flag: '🇦🇿', dialCode: '+994'),
  CountryCode(name: 'Bahamas', flag: '🇧🇸', dialCode: '+1-242'),
  CountryCode(name: 'Bahrain', flag: '🇧🇭', dialCode: '+973'),
  CountryCode(name: 'Bangladesh', flag: '🇧🇩', dialCode: '+880'),
  CountryCode(name: 'Belarus', flag: '🇧🇾', dialCode: '+375'),
  CountryCode(name: 'Belgium', flag: '🇧🇪', dialCode: '+32'),
  CountryCode(name: 'Belize', flag: '🇧🇿', dialCode: '+501'),
  CountryCode(name: 'Benin', flag: '🇧🇯', dialCode: '+229'),
  CountryCode(name: 'Bhutan', flag: '🇧🇹', dialCode: '+975'),
  CountryCode(name: 'Bolivia', flag: '🇧🇴', dialCode: '+591'),
  CountryCode(name: 'Bosnia and Herzegovina', flag: '🇧🇦', dialCode: '+387'),
  CountryCode(name: 'Botswana', flag: '🇧🇼', dialCode: '+267'),
  CountryCode(name: 'Brazil', flag: '🇧🇷', dialCode: '+55'),
  CountryCode(name: 'Brunei', flag: '🇧🇳', dialCode: '+673'),
  CountryCode(name: 'Bulgaria', flag: '🇧🇬', dialCode: '+359'),
  CountryCode(name: 'Burkina Faso', flag: '🇧🇫', dialCode: '+226'),
  CountryCode(name: 'Burundi', flag: '🇧🇮', dialCode: '+257'),
  CountryCode(name: 'Cambodia', flag: '🇰🇭', dialCode: '+855'),
  CountryCode(name: 'Cameroon', flag: '🇨🇲', dialCode: '+237'),
  CountryCode(name: 'Canada', flag: '🇨🇦', dialCode: '+1'),
  CountryCode(name: 'Cape Verde', flag: '🇨🇻', dialCode: '+238'),
  CountryCode(name: 'Central African Republic', flag: '🇨🇫', dialCode: '+236'),
  CountryCode(name: 'Chad', flag: '🇹🇩', dialCode: '+235'),
  CountryCode(name: 'Chile', flag: '🇨🇱', dialCode: '+56'),
  CountryCode(name: 'China', flag: '🇨🇳', dialCode: '+86'),
  CountryCode(name: 'Colombia', flag: '🇨🇴', dialCode: '+57'),
  CountryCode(name: 'Comoros', flag: '🇰🇲', dialCode: '+269'),
  CountryCode(name: 'Congo', flag: '🇨🇬', dialCode: '+242'),
  CountryCode(name: 'Costa Rica', flag: '🇨🇷', dialCode: '+506'),
  CountryCode(name: 'Croatia', flag: '🇭🇷', dialCode: '+385'),
  CountryCode(name: 'Cuba', flag: '🇨🇺', dialCode: '+53'),
  CountryCode(name: 'Cyprus', flag: '🇨🇾', dialCode: '+357'),
  CountryCode(name: 'Czech Republic', flag: '🇨🇿', dialCode: '+420'),
  CountryCode(name: 'Denmark', flag: '🇩🇰', dialCode: '+45'),
  CountryCode(name: 'Djibouti', flag: '🇩🇯', dialCode: '+253'),
  CountryCode(name: 'Dominican Republic', flag: '🇩🇴', dialCode: '+1-809'),
  CountryCode(name: 'Ecuador', flag: '🇪🇨', dialCode: '+593'),
  CountryCode(name: 'Egypt', flag: '🇪🇬', dialCode: '+20'),
  CountryCode(name: 'El Salvador', flag: '🇸🇻', dialCode: '+503'),
  CountryCode(name: 'Equatorial Guinea', flag: '🇬🇶', dialCode: '+240'),
  CountryCode(name: 'Eritrea', flag: '🇪🇷', dialCode: '+291'),
  CountryCode(name: 'Estonia', flag: '🇪🇪', dialCode: '+372'),
  CountryCode(name: 'Eswatini', flag: '🇸🇿', dialCode: '+268'),
  CountryCode(name: 'Ethiopia', flag: '🇪🇹', dialCode: '+251'),
  CountryCode(name: 'Fiji', flag: '🇫🇯', dialCode: '+679'),
  CountryCode(name: 'Finland', flag: '🇫🇮', dialCode: '+358'),
  CountryCode(name: 'France', flag: '🇫🇷', dialCode: '+33'),
  CountryCode(name: 'Gabon', flag: '🇬🇦', dialCode: '+241'),
  CountryCode(name: 'Gambia', flag: '🇬🇲', dialCode: '+220'),
  CountryCode(name: 'Georgia', flag: '🇬🇪', dialCode: '+995'),
  CountryCode(name: 'Germany', flag: '🇩🇪', dialCode: '+49'),
  CountryCode(name: 'Ghana', flag: '🇬🇭', dialCode: '+233'),
  CountryCode(name: 'Greece', flag: '🇬🇷', dialCode: '+30'),
  CountryCode(name: 'Guatemala', flag: '🇬🇹', dialCode: '+502'),
  CountryCode(name: 'Guinea', flag: '🇬🇳', dialCode: '+224'),
  CountryCode(name: 'Guinea-Bissau', flag: '🇬🇼', dialCode: '+245'),
  CountryCode(name: 'Guyana', flag: '🇬🇾', dialCode: '+592'),
  CountryCode(name: 'Haiti', flag: '🇭🇹', dialCode: '+509'),
  CountryCode(name: 'Honduras', flag: '🇭🇳', dialCode: '+504'),
  CountryCode(name: 'Hungary', flag: '🇭🇺', dialCode: '+36'),
  CountryCode(name: 'Iceland', flag: '🇮🇸', dialCode: '+354'),
  CountryCode(name: 'Indonesia', flag: '🇮🇩', dialCode: '+62'),
  CountryCode(name: 'Iran', flag: '🇮🇷', dialCode: '+98'),
  CountryCode(name: 'Iraq', flag: '🇮🇶', dialCode: '+964'),
  CountryCode(name: 'Ireland', flag: '🇮🇪', dialCode: '+353'),
  CountryCode(name: 'Israel', flag: '🇮🇱', dialCode: '+972'),
  CountryCode(name: 'Italy', flag: '🇮🇹', dialCode: '+39'),
  CountryCode(name: 'Jamaica', flag: '🇯🇲', dialCode: '+1-876'),
  CountryCode(name: 'Japan', flag: '🇯🇵', dialCode: '+81'),
  CountryCode(name: 'Jordan', flag: '🇯🇴', dialCode: '+962'),
  CountryCode(name: 'Kazakhstan', flag: '🇰🇿', dialCode: '+7'),
  CountryCode(name: 'Kenya', flag: '🇰🇪', dialCode: '+254'),
  CountryCode(name: 'Kuwait', flag: '🇰🇼', dialCode: '+965'),
  CountryCode(name: 'Kyrgyzstan', flag: '🇰🇬', dialCode: '+996'),
  CountryCode(name: 'Laos', flag: '🇱🇦', dialCode: '+856'),
  CountryCode(name: 'Latvia', flag: '🇱🇻', dialCode: '+371'),
  CountryCode(name: 'Lebanon', flag: '🇱🇧', dialCode: '+961'),
  CountryCode(name: 'Lesotho', flag: '🇱🇸', dialCode: '+266'),
  CountryCode(name: 'Liberia', flag: '🇱🇷', dialCode: '+231'),
  CountryCode(name: 'Libya', flag: '🇱🇾', dialCode: '+218'),
  CountryCode(name: 'Liechtenstein', flag: '🇱🇮', dialCode: '+423'),
  CountryCode(name: 'Lithuania', flag: '🇱🇹', dialCode: '+370'),
  CountryCode(name: 'Luxembourg', flag: '🇱🇺', dialCode: '+352'),
  CountryCode(name: 'Madagascar', flag: '🇲🇬', dialCode: '+261'),
  CountryCode(name: 'Malawi', flag: '🇲🇼', dialCode: '+265'),
  CountryCode(name: 'Malaysia', flag: '🇲🇾', dialCode: '+60'),
  CountryCode(name: 'Maldives', flag: '🇲🇻', dialCode: '+960'),
  CountryCode(name: 'Mali', flag: '🇲🇱', dialCode: '+223'),
  CountryCode(name: 'Malta', flag: '🇲🇹', dialCode: '+356'),
  CountryCode(name: 'Mauritania', flag: '🇲🇷', dialCode: '+222'),
  CountryCode(name: 'Mauritius', flag: '🇲🇺', dialCode: '+230'),
  CountryCode(name: 'Mexico', flag: '🇲🇽', dialCode: '+52'),
  CountryCode(name: 'Moldova', flag: '🇲🇩', dialCode: '+373'),
  CountryCode(name: 'Monaco', flag: '🇲🇨', dialCode: '+377'),
  CountryCode(name: 'Mongolia', flag: '🇲🇳', dialCode: '+976'),
  CountryCode(name: 'Montenegro', flag: '🇲🇪', dialCode: '+382'),
  CountryCode(name: 'Morocco', flag: '🇲🇦', dialCode: '+212'),
  CountryCode(name: 'Mozambique', flag: '🇲🇿', dialCode: '+258'),
  CountryCode(name: 'Myanmar', flag: '🇲🇲', dialCode: '+95'),
  CountryCode(name: 'Namibia', flag: '🇳🇦', dialCode: '+264'),
  CountryCode(name: 'Nepal', flag: '🇳🇵', dialCode: '+977'),
  CountryCode(name: 'Netherlands', flag: '🇳🇱', dialCode: '+31'),
  CountryCode(name: 'New Zealand', flag: '🇳🇿', dialCode: '+64'),
  CountryCode(name: 'Nicaragua', flag: '🇳🇮', dialCode: '+505'),
  CountryCode(name: 'Niger', flag: '🇳🇪', dialCode: '+227'),
  CountryCode(name: 'Nigeria', flag: '🇳🇬', dialCode: '+234'),
  CountryCode(name: 'North Korea', flag: '🇰🇵', dialCode: '+850'),
  CountryCode(name: 'North Macedonia', flag: '🇲🇰', dialCode: '+389'),
  CountryCode(name: 'Norway', flag: '🇳🇴', dialCode: '+47'),
  CountryCode(name: 'Oman', flag: '🇴🇲', dialCode: '+968'),
  CountryCode(name: 'Pakistan', flag: '🇵🇰', dialCode: '+92'),
  CountryCode(name: 'Palestine', flag: '🇵🇸', dialCode: '+970'),
  CountryCode(name: 'Panama', flag: '🇵🇦', dialCode: '+507'),
  CountryCode(name: 'Papua New Guinea', flag: '🇵🇬', dialCode: '+675'),
  CountryCode(name: 'Paraguay', flag: '🇵🇾', dialCode: '+595'),
  CountryCode(name: 'Peru', flag: '🇵🇪', dialCode: '+51'),
  CountryCode(name: 'Philippines', flag: '🇵🇭', dialCode: '+63'),
  CountryCode(name: 'Poland', flag: '🇵🇱', dialCode: '+48'),
  CountryCode(name: 'Portugal', flag: '🇵🇹', dialCode: '+351'),
  CountryCode(name: 'Qatar', flag: '🇶🇦', dialCode: '+974'),
  CountryCode(name: 'Romania', flag: '🇷🇴', dialCode: '+40'),
  CountryCode(name: 'Russia', flag: '🇷🇺', dialCode: '+7'),
  CountryCode(name: 'Rwanda', flag: '🇷🇼', dialCode: '+250'),
  CountryCode(name: 'Saudi Arabia', flag: '🇸🇦', dialCode: '+966'),
  CountryCode(name: 'Senegal', flag: '🇸🇳', dialCode: '+221'),
  CountryCode(name: 'Serbia', flag: '🇷🇸', dialCode: '+381'),
  CountryCode(name: 'Sierra Leone', flag: '🇸🇱', dialCode: '+232'),
  CountryCode(name: 'Singapore', flag: '🇸🇬', dialCode: '+65'),
  CountryCode(name: 'Slovakia', flag: '🇸🇰', dialCode: '+421'),
  CountryCode(name: 'Slovenia', flag: '🇸🇮', dialCode: '+386'),
  CountryCode(name: 'Somalia', flag: '🇸🇴', dialCode: '+252'),
  CountryCode(name: 'South Africa', flag: '🇿🇦', dialCode: '+27'),
  CountryCode(name: 'South Korea', flag: '🇰🇷', dialCode: '+82'),
  CountryCode(name: 'South Sudan', flag: '🇸🇸', dialCode: '+211'),
  CountryCode(name: 'Spain', flag: '🇪🇸', dialCode: '+34'),
  CountryCode(name: 'Sri Lanka', flag: '🇱🇰', dialCode: '+94'),
  CountryCode(name: 'Sudan', flag: '🇸🇩', dialCode: '+249'),
  CountryCode(name: 'Suriname', flag: '🇸🇷', dialCode: '+597'),
  CountryCode(name: 'Sweden', flag: '🇸🇪', dialCode: '+46'),
  CountryCode(name: 'Switzerland', flag: '🇨🇭', dialCode: '+41'),
  CountryCode(name: 'Syria', flag: '🇸🇾', dialCode: '+963'),
  CountryCode(name: 'Taiwan', flag: '🇹🇼', dialCode: '+886'),
  CountryCode(name: 'Tajikistan', flag: '🇹🇯', dialCode: '+992'),
  CountryCode(name: 'Tanzania', flag: '🇹🇿', dialCode: '+255'),
  CountryCode(name: 'Thailand', flag: '🇹🇭', dialCode: '+66'),
  CountryCode(name: 'Timor-Leste', flag: '🇹🇱', dialCode: '+670'),
  CountryCode(name: 'Togo', flag: '🇹🇬', dialCode: '+228'),
  CountryCode(name: 'Trinidad and Tobago', flag: '🇹🇹', dialCode: '+1-868'),
  CountryCode(name: 'Tunisia', flag: '🇹🇳', dialCode: '+216'),
  CountryCode(name: 'Turkey', flag: '🇹🇷', dialCode: '+90'),
  CountryCode(name: 'Turkmenistan', flag: '🇹🇲', dialCode: '+993'),
  CountryCode(name: 'Uganda', flag: '🇺🇬', dialCode: '+256'),
  CountryCode(name: 'Ukraine', flag: '🇺🇦', dialCode: '+380'),
  CountryCode(name: 'United Arab Emirates', flag: '🇦🇪', dialCode: '+971'),
  CountryCode(name: 'Uruguay', flag: '🇺🇾', dialCode: '+598'),
  CountryCode(name: 'Uzbekistan', flag: '🇺🇿', dialCode: '+998'),
  CountryCode(name: 'Venezuela', flag: '🇻🇪', dialCode: '+58'),
  CountryCode(name: 'Vietnam', flag: '🇻🇳', dialCode: '+84'),
  CountryCode(name: 'Yemen', flag: '🇾🇪', dialCode: '+967'),
  CountryCode(name: 'Zambia', flag: '🇿🇲', dialCode: '+260'),
  CountryCode(name: 'Zimbabwe', flag: '🇿🇼', dialCode: '+263'),
];
